services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: velivert_postgres
    environment:
      POSTGRES_DB: velivert_db
      POSTGRES_USER: velivert_user
      POSTGRES_PASSWORD: velivert_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U velivert_user -d velivert_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: velivert_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: velivert_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: velivert_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql://velivert_user:velivert_pass@postgres:5432/velivert_db
      REDIS_URL: redis://redis:6379/0
      GBFS_BASE_URL: https://api.saint-etienne-metropole.fr/velivert/api
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: velivert_celery_worker
    command: celery -A app.tasks.celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql://velivert_user:velivert_pass@postgres:5432/velivert_db
      REDIS_URL: redis://redis:6379/0
      GBFS_BASE_URL: https://api.saint-etienne-metropole.fr/velivert/api
    depends_on:
      - postgres
      - redis

  celery_beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: velivert_celery_beat
    command: celery -A app.tasks.celery_app beat --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql://velivert_user:velivert_pass@postgres:5432/velivert_db
      REDIS_URL: redis://redis:6379/0
      GBFS_BASE_URL: https://api.saint-etienne-metropole.fr/velivert/api
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: velivert_frontend
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:8000
      VITE_WS_URL: ws://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data: